[package]
license = "BSD-4-Clause"
name = "test_helpers"
version = "0.1.0"
authors = ["akhramov"]
edition = "2018"

[dependencies]
mockito = "0.25.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tokio = "0.2.18"