[package]
name = "storage"
version = "0.1.0"
authors = ["Artem Khramov <akhramov@pm.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.42"
bincode = "1.2.1"
fehler = "1.0"
serde = "1.0"
sled = "0.34"

[dev-dependencies]
tempfile = "3.1.0"